spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: ${DB_USERNAME:todolist}
    password: ${DB_PASSWORD:todolist}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.example.todolist: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
